language: php

php:
  - 5.6

branches:
  except:
    - gh-pages

before_script:
  - composer install -n --prefer-source
  - ./vendor/bin/codecept build
  - chmod 777 ./db/d3x-tst.sqlite

script:
  - ./vendor/bin/codecept run

notifications:
  slack: codeplex:mLURPasP3TW0YOAz2oolncac