language: php

php:
  - 5.6

branches:
  except:
    - gh-pages

before_script:
  - composer install -n --prefer-dist
  - ./vendor/bin/codecept build

script:
  - ./vendor/bin/codecept run

notifications:
  slack: donbstringham:uSrXFfUaMNvRj3I8tQHWDH1j
