language: php

php:
  - 5.6

branches:
  except:
    - gh-pages

before_script:
  - composer install -n --prefer-source
  - ./vendor/bin/codecept build
  - chmod -R o+w ./db

script:
  - ./vendor/bin/codecept run

notifications:
  slack: code-ninja-io:uSrXFfUaMNvRj3I8tQHWDH1j
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6e529900a435f00af885
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false